import {
  User,
  Case,
  Document,
  EvidenceItem,
  EvidenceEvent,
  AuditEvent,
  Approval,
  Alert,
  SystemSettings,
  BorderInterceptRecord,
  SigintRecord,
  DefenceIntelDossier
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-010',
    fullName: 'Col. Devendra Rathore',
    email: 'defence@justicevault.demo',
    role: 'Defence Officer',
    department: 'Joint Defence Intelligence & Border Command',
    organization: 'National Defence & Intelligence Directorate',
    phone: '+1 (555) 018-7711',
    status: 'Active',
    lastLogin: '2026-09-02 10:14:00',
    mfaEnabled: true,
    avatarInitials: 'DR',
    badgeNumber: 'DEF-CMD-001'
  },
  {
    id: 'USR-001',
    fullName: 'Dr. Sarah Jenkins',
    email: 'admin@justicevault.demo',
    role: 'Administrator',
    department: 'Directorate of Information Security',
    organization: 'Central Law Enforcement Agency',
    phone: '+1 (555) 019-2834',
    status: 'Active',
    lastLogin: '2026-09-02 08:15:22',
    mfaEnabled: true,
    avatarInitials: 'SJ',
    badgeNumber: 'SEC-ADM-901'
  },
  {
    id: 'USR-002',
    fullName: 'Inspector Kavya Rao',
    email: 'officer@justicevault.demo',
    role: 'Investigating Officer',
    department: 'Special Crime Investigation Branch',
    organization: 'Metropolitan Police Department',
    phone: '+1 (555) 014-9821',
    status: 'Active',
    lastLogin: '2026-09-02 09:42:10',
    mfaEnabled: true,
    avatarInitials: 'KR',
    badgeNumber: 'DET-4821'
  },
  {
    id: 'USR-003',
    fullName: 'Dr. Asha Menon',
    email: 'forensic@justicevault.demo',
    role: 'Forensic Officer',
    department: 'Digital & Physical Forensics Division',
    organization: 'Central Forensic Science Laboratory',
    phone: '+1 (555) 018-3419',
    status: 'Active',
    lastLogin: '2026-09-02 07:50:00',
    mfaEnabled: true,
    avatarInitials: 'AM',
    badgeNumber: 'FOR-1092'
  },
  {
    id: 'USR-004',
    fullName: 'Adv. Vikramaditya Sen',
    email: 'prosecutor@justicevault.demo',
    role: 'Prosecutor',
    department: 'Public Prosecution Office',
    organization: 'State Department of Justice',
    phone: '+1 (555) 012-7788',
    status: 'Active',
    lastLogin: '2026-09-01 16:30:14',
    mfaEnabled: true,
    avatarInitials: 'VS',
    badgeNumber: 'PROS-552'
  },
  {
    id: 'USR-005',
    fullName: 'Marcus Vance',
    email: 'auditor@justicevault.demo',
    role: 'Auditor',
    department: 'Judicial Oversight & Compliance',
    organization: 'Independent Police Oversight Board',
    phone: '+1 (555) 017-6623',
    status: 'Active',
    lastLogin: '2026-09-02 06:12:44',
    mfaEnabled: true,
    avatarInitials: 'MV',
    badgeNumber: 'AUD-007'
  },
  {
    id: 'USR-006',
    fullName: 'Hon. Registrar Evelyn Cross',
    email: 'court@justicevault.demo',
    role: 'Court Officer',
    department: 'Registry of High Court',
    organization: 'Judiciary Directorate',
    phone: '+1 (555) 011-2299',
    status: 'Active',
    lastLogin: '2026-09-01 14:20:00',
    mfaEnabled: true,
    avatarInitials: 'EC',
    badgeNumber: 'CRT-771'
  },
  {
    id: 'USR-007',
    fullName: 'Legal Officer Neha Iyer',
    email: 'legal@justicevault.demo',
    role: 'Legal Officer',
    department: 'Civil Litigation & Land Registry',
    organization: 'State Legal Services Authority',
    phone: '+1 (555) 013-4455',
    status: 'Active',
    lastLogin: '2026-09-02 09:10:18',
    mfaEnabled: true,
    avatarInitials: 'NI',
    badgeNumber: 'LEG-304'
  },
  {
    id: 'USR-008',
    fullName: 'Officer Rohan Das',
    email: 'rohan.das@justicevault.demo',
    role: 'Investigating Officer',
    department: 'Cyber Crime Investigation Cell',
    organization: 'Federal Bureau of Investigation Cyber Wing',
    phone: '+1 (555) 015-8833',
    status: 'Active',
    lastLogin: '2026-09-02 08:30:00',
    mfaEnabled: true,
    avatarInitials: 'RD',
    badgeNumber: 'CYB-882'
  },
  {
    id: 'USR-009',
    fullName: 'Claire Sterling',
    email: 'reviewer@justicevault.demo',
    role: 'Read-Only Reviewer',
    department: 'External Legal Advisory Panel',
    organization: 'National Legal Aid Foundation',
    phone: '+1 (555) 016-9900',
    status: 'Active',
    lastLogin: '2026-08-30 11:05:22',
    mfaEnabled: true,
    avatarInitials: 'CS',
    badgeNumber: 'REV-101'
  }
];

export const INITIAL_CASES: Case[] = [
  {
    id: 'CASE-001',
    caseNumber: 'JV-2026-001',
    title: 'State v. Arjun Mehta',
    category: 'Criminal Investigation',
    description: 'High-profile commercial extortion and aggravated financial fraud inquiry involving altered digital transaction records.',
    status: 'Active',
    priority: 'High',
    confidentiality: 'Restricted',
    department: 'Special Crime Investigation Branch',
    investigatingOfficer: 'Inspector Kavya Rao',
    assignedUsers: ['USR-002', 'USR-003', 'USR-004', 'USR-001'],
    openedDate: '2026-06-12',
    nextHearingDate: '2026-09-18',
    documentCount: 8,
    evidenceCount: 4,
    progressPercentage: 75,
    jurisdiction: 'Sessions Court Division 4',
    courtName: 'High Court of Criminal Judicature',
    tags: ['Financial Fraud', 'Digital Extortion', 'Seized Ledger', 'Wiretap']
  },
  {
    id: 'CASE-002',
    caseNumber: 'JV-2026-002',
    title: 'Cyber Fraud Investigation',
    category: 'Cybercrime',
    description: 'Multi-vector ransomware extortion and unauthorized exfiltration of critical municipal infrastructure data.',
    status: 'Under Review',
    priority: 'Critical',
    confidentiality: 'Highly Restricted',
    department: 'Cyber Crime Investigation Cell',
    investigatingOfficer: 'Officer Rohan Das',
    assignedUsers: ['USR-008', 'USR-003', 'USR-004', 'USR-001'],
    openedDate: '2026-07-04',
    nextHearingDate: '2026-09-25',
    documentCount: 12,
    evidenceCount: 6,
    progressPercentage: 60,
    jurisdiction: 'National Cyber Security Tribunal',
    courtName: 'Federal Cyber Offences Court',
    tags: ['Ransomware', 'Memory Dump', 'Crypto Wallet', 'Darknet']
  },
  {
    id: 'CASE-003',
    caseNumber: 'JV-2026-003',
    title: 'Property Dispute Records',
    category: 'Civil Legal Matter',
    description: 'Contested municipal land title and heritage commercial estate ownership claims involving falsified land registry archives from 1998.',
    status: 'Court Submission',
    priority: 'Medium',
    confidentiality: 'Confidential',
    department: 'Civil Litigation & Land Registry',
    investigatingOfficer: 'Legal Officer Neha Iyer',
    assignedUsers: ['USR-007', 'USR-004', 'USR-006'],
    openedDate: '2026-05-20',
    nextHearingDate: '2026-09-10',
    documentCount: 6,
    evidenceCount: 2,
    progressPercentage: 90,
    jurisdiction: 'District Civil Court 2',
    courtName: 'Principal Civil Court',
    tags: ['Land Title', 'Deed Audit', 'Survey Report', 'Deed of Conveyance']
  },
  {
    id: 'CASE-004',
    caseNumber: 'JV-2026-004',
    title: 'Harbor Logistics Narcotics Seizure',
    category: 'Narcotics & Smuggling',
    description: 'Intercepted illicit maritime shipment at Container Terminal 4 with biometric inspection logs and shipping manifest discrepancies.',
    status: 'Active',
    priority: 'High',
    confidentiality: 'Restricted',
    department: 'Special Crime Investigation Branch',
    investigatingOfficer: 'Inspector Kavya Rao',
    assignedUsers: ['USR-002', 'USR-003', 'USR-004'],
    openedDate: '2026-08-01',
    nextHearingDate: '2026-10-02',
    documentCount: 5,
    evidenceCount: 3,
    progressPercentage: 45,
    jurisdiction: 'Customs & Narcotics Special Bench',
    courtName: 'Special Narcotics Court',
    tags: ['Customs Seizure', 'Port Security', 'Chemical Test', 'Bill of Lading']
  },
  {
    id: 'CASE-005',
    caseNumber: 'JV-DEF-2026-009',
    title: 'Operation Sentinel: Transnational Border Infiltration & SIGINT Intercept',
    category: 'National Security & Defence Intelligence',
    description: 'Joint defence operation investigating hostile drone reconnaissance, encrypted satellite frequency breaches, and perimeter anomalies along Sector 7 high-altitude border outpost.',
    status: 'Active',
    priority: 'Critical',
    confidentiality: 'Top Secret // SAP',
    department: 'Joint Defence Intelligence & Border Command',
    investigatingOfficer: 'Col. Devendra Rathore',
    assignedUsers: ['USR-010', 'USR-001', 'USR-002', 'USR-003', 'USR-008'],
    openedDate: '2026-08-10',
    nextHearingDate: '2026-09-22',
    documentCount: 7,
    evidenceCount: 4,
    progressPercentage: 88,
    jurisdiction: 'Armed Forces & National Security Appellate Bench',
    courtName: 'Special Military & National Security Tribunal',
    tags: ['National Security', 'Smart Surveillance', 'Border Management', 'SIGINT Intercept', 'UAV Scan', 'Top Secret']
  }
];

export const INITIAL_DOCUMENTS: Document[] = [
  {
    id: 'DOC-001',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    fileName: 'FIR_2026_089_ArjunMehta.pdf',
    documentType: 'First Information Report (FIR)',
    description: 'Official First Information Report filed at Central Police Station regarding corporate embezzlement and extortion threats.',
    uploadedBy: 'Inspector Kavya Rao',
    department: 'Special Crime Investigation Branch',
    version: 4,
    fileSize: '2.84 MB',
    fileFormat: 'PDF',
    status: 'Submitted',
    confidentiality: 'Restricted',
    uploadedAt: '2026-06-12 10:14:32',
    lastModifiedAt: '2026-08-28 14:10:00',
    sha256Hash: 'a13f8b9d7c1e2f4a8d5c6b7e9f00123456789abcdef0123456789abcdef0123',
    blockchainTransactionId: '0xJV2026DOC8F4A91C7B2E',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Hon. Registrar Evelyn Cross (Court Registry)',
    tags: ['FIR', 'Official Complaint', 'Police Seal', 'Court-Ready'],
    signedBy: 'Adv. Vikramaditya Sen (Prosecutor)',
    signedAt: '2026-08-25 11:20:00',
    contentSnippet: 'Complainant Shri R. K. Singhania alleges that suspect Arjun Mehta fabricated board authorizations to siphon USD 1.4M into offshore shadow accounts...',
    versions: [
      {
        version: 1,
        fileName: 'FIR_2026_089_ArjunMehta_draft.pdf',
        uploadedAt: '2026-06-12 10:14:32',
        uploadedBy: 'Inspector Kavya Rao',
        fileSize: '2.61 MB',
        sha256Hash: '9c48f8b19e2e4a8d5c6b7e9f00123456789abcdef0123456789abcdef0123aa',
        blockchainTransactionId: '0xJV2026DOC111A91C7B1A',
        signatureStatus: 'Unsigned',
        changesSummary: 'Initial police report draft uploaded directly from Station Log.'
      },
      {
        version: 2,
        fileName: 'FIR_2026_089_ArjunMehta_reviewed.pdf',
        uploadedAt: '2026-06-20 15:30:10',
        uploadedBy: 'Inspector Kavya Rao',
        fileSize: '2.70 MB',
        sha256Hash: 'e713f8b9d7c1e2f4a8d5c6b7e9f00123456789abcdef0123456789abcdef01bb',
        blockchainTransactionId: '0xJV2026DOC222A91C7B2B',
        signatureStatus: 'Unsigned',
        changesSummary: 'Reviewed by Senior Investigator; attached annexure of witness identities.'
      },
      {
        version: 3,
        fileName: 'FIR_2026_089_ArjunMehta_signed.pdf',
        uploadedAt: '2026-08-25 11:20:00',
        uploadedBy: 'Adv. Vikramaditya Sen',
        fileSize: '2.84 MB',
        sha256Hash: 'a13f8b9d7c1e2f4a8d5c6b7e9f00123456789abcdef0123456789abcdef0123',
        blockchainTransactionId: '0xJV2026DOC8F4A91C7B2E',
        signatureStatus: 'Digitally Signed',
        changesSummary: 'Prosecution verification completed and cryptographic signature token attached.'
      },
      {
        version: 4,
        fileName: 'FIR_2026_089_ArjunMehta_court_submission.pdf',
        uploadedAt: '2026-08-28 14:10:00',
        uploadedBy: 'Adv. Vikramaditya Sen',
        fileSize: '2.84 MB',
        sha256Hash: 'a13f8b9d7c1e2f4a8d5c6b7e9f00123456789abcdef0123456789abcdef0123',
        blockchainTransactionId: '0xJV2026DOC8F4A91C7B2E',
        signatureStatus: 'Digitally Signed',
        changesSummary: 'Submitted to Sessions Court Registry and marked Exhibit P-1.'
      }
    ]
  },
  {
    id: 'DOC-002',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    fileName: 'Forensic_Analysis_ServerLog_v2.pdf',
    documentType: 'Forensic Analysis Report',
    description: 'Technical analysis of IP connections, database alterations, and cryptographic hash comparisons of internal financial ERP ledger.',
    uploadedBy: 'Dr. Asha Menon',
    department: 'Digital & Physical Forensics Division',
    version: 2,
    fileSize: '5.12 MB',
    fileFormat: 'PDF',
    status: 'Approved',
    confidentiality: 'Restricted',
    uploadedAt: '2026-07-15 16:45:00',
    lastModifiedAt: '2026-07-22 09:12:00',
    sha256Hash: '4f92d81a7b8c3e0f91a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4',
    blockchainTransactionId: '0xJV2026TX7C9B2E1D8A4F',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Adv. Vikramaditya Sen (Prosecutor)',
    tags: ['Forensic Report', 'Server Log', 'Digital Trail', 'ERP DB'],
    signedBy: 'Dr. Asha Menon (Chief Forensic Examiner)',
    signedAt: '2026-07-22 09:10:00',
    contentSnippet: 'Memory extraction reveals user credentials for admin session originated from VPN egress gateway in Zurich on May 29, 2026 at 02:14:09 UTC.'
  },
  {
    id: 'DOC-003',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    fileName: 'Witness_Statement_RKSinghania.pdf',
    documentType: 'Witness Statement',
    description: 'Sworn deposition of key witness regarding unauthorized fund transfer requests received via internal encrypted communicator.',
    uploadedBy: 'Inspector Kavya Rao',
    department: 'Special Crime Investigation Branch',
    version: 1,
    fileSize: '1.45 MB',
    fileFormat: 'PDF',
    status: 'Approved',
    confidentiality: 'Confidential',
    uploadedAt: '2026-06-25 14:00:10',
    lastModifiedAt: '2026-06-25 14:00:10',
    sha256Hash: '8b7e9f00123456789abcdef0123456789abcdef0123a13f8b9d7c1e2f4a8d5c6',
    blockchainTransactionId: '0xJV2026TX198A44C2D7B1',
    signatureStatus: 'Verified',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Inspector Kavya Rao',
    tags: ['Witness', 'Sworn Deposition', 'Audio Transcription'],
    contentSnippet: 'Witness states that meetings took place on May 15 and May 22, wherein suspect demanded escrow release under threat of commercial sabotage.'
  },
  {
    id: 'DOC-004',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    fileName: 'Search_And_Seizure_Memo_MehtaResidence.pdf',
    documentType: 'Search and Seizure Memo',
    description: 'Inventory of seized electronic storage units, encrypted hard drives, and private ledgers from suspect premises.',
    uploadedBy: 'Inspector Kavya Rao',
    department: 'Special Crime Investigation Branch',
    version: 1,
    fileSize: '3.30 MB',
    fileFormat: 'PDF',
    status: 'Approved',
    confidentiality: 'Restricted',
    uploadedAt: '2026-06-18 19:22:40',
    lastModifiedAt: '2026-06-18 19:22:40',
    sha256Hash: '3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e44f92d81a7b8c3e0f91a2b',
    blockchainTransactionId: '0xJV2026TX55B81C9A0F22',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Dr. Asha Menon (Forensic Lab)',
    tags: ['Seizure Memo', 'Evidence Log', 'Hardware Recovery'],
    signedBy: 'Inspector Kavya Rao',
    signedAt: '2026-06-18 19:20:00'
  },
  {
    id: 'DOC-005',
    caseId: 'CASE-002',
    caseNumber: 'JV-2026-002',
    fileName: 'Malware_Reverse_Engineering_Report_LockBitX.pdf',
    documentType: 'Forensic Analysis Report',
    description: 'Comprehensive static and dynamic reverse-engineering of custom ransom payload deployed on municipal water filtration SCADA nodes.',
    uploadedBy: 'Dr. Asha Menon',
    department: 'Digital & Physical Forensics Division',
    version: 1,
    fileSize: '8.76 MB',
    fileFormat: 'PDF',
    status: 'Under Review',
    confidentiality: 'Highly Restricted',
    uploadedAt: '2026-07-28 11:15:00',
    lastModifiedAt: '2026-07-28 11:15:00',
    sha256Hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e44f92d81a7b8c3e0f9',
    blockchainTransactionId: '0xJV2026TX999A1C8F7E4D',
    signatureStatus: 'Pending Signature',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Officer Rohan Das (Cyber Cell)',
    tags: ['Malware', 'SCADA', 'Reverse Engineering', 'Zero-Day']
  },
  {
    id: 'DOC-006',
    caseId: 'CASE-002',
    caseNumber: 'JV-2026-002',
    fileName: 'Crypto_Wallet_Trace_Chainalysis.pdf',
    documentType: 'Investigation Progress Report',
    description: 'On-chain forensic tracing report identifying mixing service hops and off-ramp KYC endpoints linked to threat actor address 0x7a8...99e.',
    uploadedBy: 'Officer Rohan Das',
    department: 'Cyber Crime Investigation Cell',
    version: 1,
    fileSize: '4.20 MB',
    fileFormat: 'PDF',
    status: 'Approved',
    confidentiality: 'Highly Restricted',
    uploadedAt: '2026-08-05 15:40:00',
    lastModifiedAt: '2026-08-05 15:40:00',
    sha256Hash: '7e8f9a0b1c2d3e44f92d81a7b8c3e0f91a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
    blockchainTransactionId: '0xJV2026TX44C11E99A02B',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Officer Rohan Das',
    tags: ['Blockchain Trace', 'Crypto KYC', 'Financial Intel']
  },
  {
    id: 'DOC-007',
    caseId: 'CASE-003',
    caseNumber: 'JV-2026-003',
    fileName: 'Deed_Of_Conveyance_Archival_Audit_1998.pdf',
    documentType: 'Legal Notice',
    description: 'High-resolution multispectral scan and archival seal verification of contested 1998 commercial land title conveyance deed.',
    uploadedBy: 'Legal Officer Neha Iyer',
    department: 'Civil Litigation & Land Registry',
    version: 2,
    fileSize: '12.40 MB',
    fileFormat: 'PDF',
    status: 'Submitted',
    confidentiality: 'Confidential',
    uploadedAt: '2026-05-24 10:00:00',
    lastModifiedAt: '2026-08-15 16:20:00',
    sha256Hash: '5c6d7e8f9a0b1c2d3e44f92d81a7b8c3e0f91a2b3c4d5e6f7a8b9c0d1e2f3a4b',
    blockchainTransactionId: '0xJV2026TX888E00B1A77F',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Hon. Registrar Evelyn Cross',
    tags: ['Land Title', 'Registry Deed', 'Archival Scan', 'Exhibit A'],
    signedBy: 'Legal Officer Neha Iyer',
    signedAt: '2026-08-15 16:15:00'
  },
  {
    id: 'DOC-008',
    caseId: 'CASE-003',
    caseNumber: 'JV-2026-003',
    fileName: 'Surveyor_General_Cadastral_Map_2026.pdf',
    documentType: 'Court Filing',
    description: 'Certified GPS cadastral boundary map and drone orthophoto survey of Estate Plot No. 419-B.',
    uploadedBy: 'Legal Officer Neha Iyer',
    department: 'Civil Litigation & Land Registry',
    version: 1,
    fileSize: '6.80 MB',
    fileFormat: 'PDF',
    status: 'Submitted',
    confidentiality: 'Confidential',
    uploadedAt: '2026-06-02 11:30:00',
    lastModifiedAt: '2026-06-02 11:30:00',
    sha256Hash: '9a0b1c2d3e44f92d81a7b8c3e0f91a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f',
    blockchainTransactionId: '0xJV2026TX221D44E89B10',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Hon. Registrar Evelyn Cross',
    tags: ['Cadastral Survey', 'GIS Mapping', 'Boundary Plot']
  },
  {
    id: 'DOC-009',
    caseId: 'CASE-005',
    caseNumber: 'JV-DEF-2026-009',
    fileName: 'Border_Perimeter_Thermal_Scan_Sector7.pdf',
    documentType: 'Border Surveillance Intercept Log',
    description: 'FLIR radiometric thermal imaging report and automated LiDAR telemetry showing unauthorized nocturnal border crossing attempts at Sector 7 pass.',
    uploadedBy: 'Col. Devendra Rathore',
    department: 'Joint Defence Intelligence & Border Command',
    version: 1,
    fileSize: '14.2 MB',
    fileFormat: 'PDF',
    status: 'Digitally Signed',
    confidentiality: 'Top Secret',
    uploadedAt: '2026-08-14 03:22:15',
    lastModifiedAt: '2026-08-14 04:10:00',
    sha256Hash: '7c89def0123456789abcdef0123456789abcdef0123456789abcdef012345678',
    blockchainTransactionId: '0xDEF2026TX78B91100C4A',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Col. Devendra Rathore (Sector 7 Command)',
    tags: ['Smart Surveillance', 'Border Security', 'Thermal Imaging', 'Perimeter Breach', 'Top Secret'],
    signedBy: 'Col. Devendra Rathore (Joint Defence Intelligence)',
    signedAt: '2026-08-14 04:05:00',
    contentSnippet: 'Sector 7 automated acoustic sensor array triggered at 02:44 hrs UTC. FLIR thermal pod #04 locked onto 3 unidentified human silhouettes transporting anomalous equipment packages across unmarked ridge.'
  },
  {
    id: 'DOC-010',
    caseId: 'CASE-005',
    caseNumber: 'JV-DEF-2026-009',
    fileName: 'SIGINT_Satellite_Decrypted_Cipher_Intercept.pdf',
    documentType: 'SIGINT Intercept Report',
    description: 'Intercepted trans-border military-band radio frequency transmission decrypted using AI Neural Lattice Cryptanalysis with Section 65B judicial warrant certification.',
    uploadedBy: 'Col. Devendra Rathore',
    department: 'Joint Defence Intelligence & Border Command',
    version: 2,
    fileSize: '4.75 MB',
    fileFormat: 'PDF',
    status: 'Approved',
    confidentiality: 'Top Secret // SAP',
    uploadedAt: '2026-08-18 09:15:00',
    lastModifiedAt: '2026-08-20 16:30:00',
    sha256Hash: '3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b',
    blockchainTransactionId: '0xDEF2026TX999A4400B1C',
    signatureStatus: 'Verified',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Col. Devendra Rathore',
    tags: ['SIGINT', 'Satellite Intercept', 'Cryptanalysis', 'Special Access Program', 'COMINT'],
    signedBy: 'Dr. Asha Menon (Chief Cryptographic Analyst)',
    signedAt: '2026-08-20 16:25:00',
    contentSnippet: 'Intercepted downlink on 8.412 GHz Mil-Band carrier. Cipher stream analyzed using Ed25519 hash validation. Decrypted payload details coordinated clandestine logistics drop at coordinates 34.1829 N, 74.8312 E.'
  },
  {
    id: 'DOC-011',
    caseId: 'CASE-005',
    caseNumber: 'JV-DEF-2026-009',
    fileName: 'National_Security_Directive_77B_AirGap.pdf',
    documentType: 'National Security Directive',
    description: 'Binding inter-agency sovereign directive ordering biometric credential hardening, HSM air-gapped cryptographic synchronization, and unified counter-espionage protocols.',
    uploadedBy: 'Dr. Sarah Jenkins',
    department: 'Directorate of Information Security',
    version: 1,
    fileSize: '1.88 MB',
    fileFormat: 'PDF',
    status: 'Submitted',
    confidentiality: 'Top Secret',
    uploadedAt: '2026-08-22 14:00:00',
    lastModifiedAt: '2026-08-22 14:00:00',
    sha256Hash: 'f1e2d3c4b5a60987654321fedcba0987654321fedcba0987654321fedcba0987',
    blockchainTransactionId: '0xDEF2026DIR77B1100AA',
    signatureStatus: 'Digitally Signed',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Dr. Sarah Jenkins (Directorate Admin)',
    tags: ['National Security Directive', 'Air-Gap Protocol', 'Sovereign Keys', 'Inter-Agency'],
    signedBy: 'Dr. Sarah Jenkins (Information Security Director)',
    signedAt: '2026-08-22 14:15:00',
    contentSnippet: 'By authority of the National Security Council, all evidentiary nodes handling trans-border defense intercepts must enforce zero-trust multi-party authorization and physically isolated HSM key replication.'
  },
  {
    id: 'DOC-012',
    caseId: 'CASE-005',
    caseNumber: 'JV-DEF-2026-009',
    fileName: 'UAV_Reconnaissance_Flight_Telemetry_Log.pdf',
    documentType: 'UAV Aerial Reconnaissance Scan',
    description: 'Autonomous UAV Sentinel-9 synthetic aperture radar (SAR) survey mapping concealed underground tunnel entries adjacent to international boundary line.',
    uploadedBy: 'Col. Devendra Rathore',
    department: 'Joint Defence Intelligence & Border Command',
    version: 1,
    fileSize: '8.34 MB',
    fileFormat: 'PDF',
    status: 'Approved',
    confidentiality: 'Restricted',
    uploadedAt: '2026-08-26 18:40:00',
    lastModifiedAt: '2026-08-26 18:40:00',
    sha256Hash: '5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
    blockchainTransactionId: '0xDEF2026TXUAV8811BB',
    signatureStatus: 'Verified',
    storageStatus: 'Encrypted AES-256',
    currentCustodian: 'Col. Devendra Rathore',
    tags: ['UAV Scan', 'Aerial Recon', 'SAR Radar', 'Tunnel Detection', 'Border Defence'],
    signedBy: 'Col. Devendra Rathore',
    signedAt: '2026-08-26 19:00:00',
    contentSnippet: 'SAR radar pass at 12,000 ft altitude identified linear subsurface density anomaly (depth 4.2m) extending 320 meters past the international border line toward abandoned agricultural depot.'
  }
];

export const INITIAL_EVIDENCE_ITEMS: EvidenceItem[] = [
  {
    id: 'EVD-001',
    evidenceNumber: 'EVD-2026-001A',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    title: 'Seized NVMe SSD (Samsung 990 Pro 2TB)',
    category: 'Digital',
    description: 'Primary storage unit extracted from suspect desktop workstation at residence during judicial search warrant execution.',
    collectedBy: 'Inspector Kavya Rao',
    collectionDate: '2026-06-18 18:30:00',
    currentCustodian: 'Dr. Asha Menon (Chief Forensic Examiner)',
    currentOrganization: 'Central Forensic Science Laboratory',
    currentLocation: 'Evidence Locker Vault B - Slot 42 (Faraday Enclosure)',
    integrityStatus: 'Verified',
    eventsCount: 5,
    latestBlockchainTx: '0xJV2026EVD77A1C94B2E8',
    storageRequirement: 'Static Shielding & Faraday Bag (-10°C to 25°C)',
    tags: ['NVMe', 'Hardware', 'Primary Disk', 'Encrypted BitLocker']
  },
  {
    id: 'EVD-002',
    evidenceNumber: 'EVD-2026-001B',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    title: 'Handwritten Ledger Notebook & Crypto Seed Backup',
    category: 'Documentary',
    description: 'Black Moleskine notebook containing handwritten wallet addresses, mnemonic seeds, and financial transaction dates.',
    collectedBy: 'Inspector Kavya Rao',
    collectionDate: '2026-06-18 19:10:00',
    currentCustodian: 'Adv. Vikramaditya Sen (Prosecutor)',
    currentOrganization: 'Public Prosecution Office',
    currentLocation: 'Prosecution Safe Deposit Room - Lockbox 14',
    integrityStatus: 'Verified',
    eventsCount: 6,
    latestBlockchainTx: '0xJV2026EVD999C22D11A4',
    storageRequirement: 'Climate Controlled Document Vault',
    tags: ['Physical Ledger', 'Mnemonic Words', 'Handwriting Sample']
  },
  {
    id: 'EVD-003',
    evidenceNumber: 'EVD-2026-002A',
    caseId: 'CASE-002',
    caseNumber: 'JV-2026-002',
    title: 'Industrial Router Memory Image (Cisco ISR 4331)',
    category: 'Digital',
    description: 'Volatile RAM acquisition snapshot and packet capture file recovered during live network intrusion at Municipal Utility Station.',
    collectedBy: 'Officer Rohan Das',
    collectionDate: '2026-07-05 04:15:00',
    currentCustodian: 'Dr. Asha Menon (Forensic Lab)',
    currentOrganization: 'Central Forensic Science Laboratory',
    currentLocation: 'Cyber Forensics Server Cluster - Storage Node 7',
    integrityStatus: 'Verified',
    eventsCount: 4,
    latestBlockchainTx: '0xJV2026EVD33A44B55C66',
    storageRequirement: 'Write-Blocked Cryptographic SAN',
    tags: ['Router Dump', 'Packet Capture', 'SCADA Network']
  },
  {
    id: 'EVD-004',
    evidenceNumber: 'EVD-2026-003A',
    caseId: 'CASE-003',
    caseNumber: 'JV-2026-003',
    title: 'Original Parchment Title Deed Document (Registry #419)',
    category: 'Physical',
    description: 'Contested 1998 stamp-paper land conveyance instrument submitted for ink aging spectroscopy and forensic chemical testing.',
    collectedBy: 'Legal Officer Neha Iyer',
    collectionDate: '2026-05-22 14:00:00',
    currentCustodian: 'Hon. Registrar Evelyn Cross',
    currentOrganization: 'Judiciary Directorate',
    currentLocation: 'High Court Evidence Archive Vault - Shelf 109',
    integrityStatus: 'Verified',
    eventsCount: 5,
    latestBlockchainTx: '0xJV2026EVD888F11A22C3',
    storageRequirement: 'Acid-Free Archival Enclosure (45% RH)',
    tags: ['Stamp Paper', 'Ink Analysis', 'Land Record']
  }
];

export const INITIAL_EVIDENCE_EVENTS: EvidenceEvent[] = [
  // EVD-001 Chain
  {
    id: 'EVT-001',
    evidenceId: 'EVD-001',
    caseId: 'CASE-001',
    eventType: 'EVIDENCE_COLLECTED',
    description: 'Physical recovery and forensic write-block sealing of Samsung 990 Pro 2TB SSD at suspect residence.',
    fromCustodian: 'Suspect Premises (Arjun Mehta)',
    toCustodian: 'Inspector Kavya Rao',
    organization: 'Metropolitan Police Department',
    timestamp: '2026-06-18 18:30:00',
    location: '42 Crescent Avenue, Westside Residence',
    eventHash: 'a7c9e123456789abcdef0123456789abcdef0123456789abcdef012345678901',
    blockchainTransactionId: '0xJV2026TX_EVD1_01',
    digitalSignatureStatus: 'Signed',
    verificationStatus: 'Verified',
    notes: 'Tamper-evident evidence bag #TEB-902188 applied and photographed.'
  },
  {
    id: 'EVT-002',
    evidenceId: 'EVD-001',
    caseId: 'CASE-001',
    eventType: 'EVIDENCE_REGISTERED',
    description: 'Evidence logged into Police Station secure inventory management and biometric seal verified.',
    fromCustodian: 'Inspector Kavya Rao',
    toCustodian: 'Evidence Registry Officer Mark Thorne',
    organization: 'Metropolitan Police Department',
    timestamp: '2026-06-18 21:00:00',
    location: 'Central Police Station - Evidence Depot',
    eventHash: 'b8d0f23456789abcdef0123456789abcdef0123456789abcdef012345678902',
    blockchainTransactionId: '0xJV2026TX_EVD1_02',
    digitalSignatureStatus: 'Signed',
    verificationStatus: 'Verified'
  },
  {
    id: 'EVT-003',
    evidenceId: 'EVD-001',
    caseId: 'CASE-001',
    eventType: 'CUSTODY_TRANSFERRED',
    description: 'Secure courier dispatch and transit to Central Forensic Science Laboratory for forensic bit-stream imaging.',
    fromCustodian: 'Evidence Registry Officer Mark Thorne',
    toCustodian: 'Dr. Asha Menon (Chief Forensic Examiner)',
    organization: 'Central Forensic Science Laboratory',
    timestamp: '2026-06-20 09:15:00',
    location: 'Forensic Lab Intake Station, Cyber Wing',
    eventHash: 'c9e103456789abcdef0123456789abcdef0123456789abcdef012345678903',
    blockchainTransactionId: '0xJV2026TX_EVD1_03',
    digitalSignatureStatus: 'Signed',
    verificationStatus: 'Verified',
    notes: 'Seal #TEB-902188 inspected under UV light; intact without micro-fissures.'
  },
  {
    id: 'EVT-004',
    evidenceId: 'EVD-001',
    caseId: 'CASE-001',
    eventType: 'FORENSIC_IMAGING_COMPLETED',
    description: 'Bit-stream forensic clone created (E01 format) via hardware write-blocker Tableau T8u. MD5 and SHA-256 verified identical.',
    fromCustodian: 'Dr. Asha Menon',
    toCustodian: 'Dr. Asha Menon',
    organization: 'Central Forensic Science Laboratory',
    timestamp: '2026-06-21 14:40:00',
    location: 'Forensic Cleanroom Lab 3',
    eventHash: 'd0f21456789abcdef0123456789abcdef0123456789abcdef012345678904',
    blockchainTransactionId: '0xJV2026TX_EVD1_04',
    digitalSignatureStatus: 'Signed',
    verificationStatus: 'Verified'
  },
  {
    id: 'EVT-005',
    evidenceId: 'EVD-001',
    caseId: 'CASE-001',
    eventType: 'VAULT_STORAGE_DEPOSIT',
    description: 'Original SSD placed in Faraday Vault Locker B-42 pending trial examination.',
    fromCustodian: 'Dr. Asha Menon',
    toCustodian: 'Dr. Asha Menon (Chief Forensic Examiner)',
    organization: 'Central Forensic Science Laboratory',
    timestamp: '2026-07-22 10:00:00',
    location: 'Evidence Locker Vault B - Slot 42',
    eventHash: 'e1a3256789abcdef0123456789abcdef0123456789abcdef012345678905',
    blockchainTransactionId: '0xJV2026EVD77A1C94B2E8',
    digitalSignatureStatus: 'Signed',
    verificationStatus: 'Verified'
  },

  // EVD-002 Chain
  {
    id: 'EVT-006',
    evidenceId: 'EVD-002',
    caseId: 'CASE-001',
    eventType: 'EVIDENCE_COLLECTED',
    description: 'Black Moleskine notebook containing handwritten crypto private keys seized and logged.',
    fromCustodian: 'Suspect Premises (Arjun Mehta)',
    toCustodian: 'Inspector Kavya Rao',
    organization: 'Metropolitan Police Department',
    timestamp: '2026-06-18 19:10:00',
    location: '42 Crescent Avenue, Westside Residence',
    eventHash: 'f2b436789abcdef0123456789abcdef0123456789abcdef012345678906',
    blockchainTransactionId: '0xJV2026TX_EVD2_01',
    digitalSignatureStatus: 'Signed',
    verificationStatus: 'Verified'
  },
  {
    id: 'EVT-007',
    evidenceId: 'EVD-002',
    caseId: 'CASE-001',
    eventType: 'CUSTODY_TRANSFERRED',
    description: 'Physical transfer to Public Prosecution Office for trial preparation and exhibit cataloging.',
    fromCustodian: 'Inspector Kavya Rao',
    toCustodian: 'Adv. Vikramaditya Sen (Prosecutor)',
    organization: 'Public Prosecution Office',
    timestamp: '2026-08-20 11:30:00',
    location: 'Department of Justice Building - Room 402',
    eventHash: '03c54789abcdef0123456789abcdef0123456789abcdef012345678907',
    blockchainTransactionId: '0xJV2026EVD999C22D11A4',
    digitalSignatureStatus: 'Signed',
    verificationStatus: 'Verified',
    notes: 'Signed and acknowledged in presence of Deputy Registrar.'
  }
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'AUD-991',
    action: 'SYSTEM_INTEGRITY_CHECK',
    resourceType: 'SYSTEM',
    resourceId: 'SYS-ROOT-LEDGER',
    resourceName: 'Consensus Merkle Tree',
    performedBy: 'Marcus Vance',
    role: 'Auditor',
    department: 'Judicial Oversight & Compliance',
    ipAddress: '10.240.12.88',
    device: 'Oversight-Terminal-04 (Linux 6.8)',
    timestamp: '2026-09-02 06:15:00',
    result: 'Success',
    riskLevel: 'Low',
    details: 'Automated periodic ledger verification completed. 148 hashes matched root Merkle state with 0 discrepancies.',
    eventHash: '0xAUD991789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
  },
  {
    id: 'AUD-990',
    action: 'LOGIN_SUCCESS',
    resourceType: 'AUTH',
    resourceId: 'USR-002',
    resourceName: 'Inspector Kavya Rao',
    performedBy: 'Inspector Kavya Rao',
    role: 'Investigating Officer',
    department: 'Special Crime Investigation Branch',
    ipAddress: '192.168.4.112',
    device: 'Police Secure Workstation (Windows 11 Enterprise)',
    timestamp: '2026-09-02 09:42:10',
    result: 'Success',
    riskLevel: 'Low',
    details: 'Multi-factor authentication verified via hardware OTP.'
  },
  {
    id: 'AUD-989',
    action: 'DIGITAL_SIGNATURE',
    resourceType: 'DOCUMENT',
    resourceId: 'DOC-001',
    resourceName: 'FIR_2026_089_ArjunMehta.pdf',
    performedBy: 'Adv. Vikramaditya Sen',
    role: 'Prosecutor',
    department: 'Public Prosecution Office',
    ipAddress: '10.100.8.44',
    device: 'Judicial MacBook Pro (macOS 15.1)',
    timestamp: '2026-08-28 14:10:00',
    result: 'Success',
    riskLevel: 'Low',
    details: 'Digital Certificate PROS-552 applied for Sessions Court filing. Hash committed to blockchain ledger TX 0xJV2026DOC8F4A91C7B2E.'
  },
  {
    id: 'AUD-988',
    action: 'CUSTODY_TRANSFER',
    resourceType: 'EVIDENCE',
    resourceId: 'EVD-002',
    resourceName: 'Handwritten Ledger Notebook & Crypto Seed Backup',
    performedBy: 'Inspector Kavya Rao',
    role: 'Investigating Officer',
    department: 'Special Crime Investigation Branch',
    ipAddress: '192.168.4.112',
    device: 'Evidence Terminal Mobile Barcode Scanner',
    timestamp: '2026-08-20 11:30:00',
    result: 'Success',
    riskLevel: 'Medium',
    details: 'Physical custody handed over to Adv. Vikramaditya Sen. Dual biometric signatures recorded.'
  },
  {
    id: 'AUD-987',
    action: 'DOCUMENT_VIEW',
    resourceType: 'DOCUMENT',
    resourceId: 'DOC-005',
    resourceName: 'Malware_Reverse_Engineering_Report_LockBitX.pdf',
    performedBy: 'Officer Rohan Das',
    role: 'Investigating Officer',
    department: 'Cyber Crime Investigation Cell',
    ipAddress: '172.16.88.20',
    device: 'Cyber Forensics Analyst Rig',
    timestamp: '2026-08-19 16:02:11',
    result: 'Success',
    riskLevel: 'Low',
    details: 'Accessed classified SCADA vulnerability technical teardown.'
  },
  {
    id: 'AUD-986',
    action: 'TAMPER_ALERT_TRIGGERED',
    resourceType: 'DOCUMENT',
    resourceId: 'DOC-001',
    resourceName: 'FIR_2026_089_ArjunMehta.pdf',
    performedBy: 'System Integrity Sentinel Service',
    role: 'Administrator',
    department: 'Directorate of Information Security',
    ipAddress: '127.0.0.1',
    device: 'Sentinel Node Daemon',
    timestamp: '2026-08-18 03:22:19',
    result: 'Warning',
    riskLevel: 'Critical',
    details: 'Integrity mismatch caught: An unauthorized byte-level alteration attempt on cached buffer was blocked and logged.'
  },
  {
    id: 'AUD-985',
    action: 'PERMISSION_CHANGE',
    resourceType: 'CASE',
    resourceId: 'CASE-002',
    resourceName: 'Cyber Fraud Investigation',
    performedBy: 'Dr. Sarah Jenkins',
    role: 'Administrator',
    department: 'Directorate of Information Security',
    ipAddress: '10.240.1.1',
    device: 'Admin Console 01',
    timestamp: '2026-08-10 11:00:00',
    result: 'Success',
    riskLevel: 'Medium',
    details: 'Elevated classification to Highly Restricted. Assigned Officer Rohan Das and Chief Forensic Officer.'
  }
];

export const INITIAL_APPROVALS: Approval[] = [
  {
    id: 'APP-001',
    documentId: 'DOC-005',
    caseId: 'CASE-002',
    caseNumber: 'JV-2026-002',
    documentName: 'Malware_Reverse_Engineering_Report_LockBitX.pdf',
    requestedBy: 'Dr. Asha Menon',
    requestedTo: 'Adv. Vikramaditya Sen (Prosecutor)',
    approvalType: 'Digital Signature',
    status: 'Pending',
    requestedAt: '2026-08-29 10:00:00',
    dueDate: '2026-09-05 18:00:00',
    comments: 'Requires prosecutor formal digital seal before submission to Federal Cyber Tribunal.',
    version: 1,
    priority: 'Critical'
  },
  {
    id: 'APP-002',
    documentId: 'DOC-001',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    documentName: 'FIR_2026_089_ArjunMehta.pdf',
    requestedBy: 'Adv. Vikramaditya Sen',
    requestedTo: 'Hon. Registrar Evelyn Cross (Court Registry)',
    approvalType: 'Court Submission',
    status: 'Approved',
    requestedAt: '2026-08-25 09:00:00',
    dueDate: '2026-08-28 17:00:00',
    completedAt: '2026-08-28 14:10:00',
    comments: 'Formally accepted and cataloged into court record as Exhibit P-1.',
    version: 4,
    priority: 'High'
  },
  {
    id: 'APP-003',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    documentName: 'Special Access Request: Offshore Wiretap Audio Transcript',
    requestedBy: 'Officer Rohan Das',
    requestedTo: 'Dr. Sarah Jenkins (Administrator)',
    approvalType: 'Access Permission Request',
    status: 'Pending',
    requestedAt: '2026-09-01 14:30:00',
    dueDate: '2026-09-04 12:00:00',
    comments: 'Cross-case correlation requested between JV-2026-001 and ransomware syndicate wallet in JV-2026-002.',
    priority: 'High'
  },
  {
    id: 'APP-004',
    documentId: 'DOC-002',
    caseId: 'CASE-001',
    caseNumber: 'JV-2026-001',
    documentName: 'Forensic_Analysis_ServerLog_v2.pdf',
    requestedBy: 'Dr. Asha Menon',
    requestedTo: 'Inspector Kavya Rao',
    approvalType: 'Document Review',
    status: 'Approved',
    requestedAt: '2026-07-20 12:00:00',
    dueDate: '2026-07-25 18:00:00',
    completedAt: '2026-07-22 09:10:00',
    comments: 'Reviewed and confirmed technical alignment with server raid seizure.',
    version: 2,
    priority: 'Medium'
  }
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-001',
    type: 'Integrity Mismatch',
    severity: 'Critical',
    title: 'Attempted modification of a digitally signed document',
    description: 'An attempted modification was detected for a digitally signed document. The recorded document hash does not match the current file hash.',
    timestamp: '2026-09-01 23:14:02',
    relatedResource: 'FIR_2026_089_ArjunMehta.pdf (DOC-001)',
    relatedCaseId: 'CASE-001',
    status: 'Under Investigation',
    recommendedAction: 'Freeze file cache immediately, re-verify Merkle chain against offline cold-storage replica, and conduct security audit.',
    assignedInvestigator: 'Inspector Kavya Rao',
    resolutionNotes: 'Preliminary analysis shows an unauthorized local temp buffer modification on Client Node 09. Production file remained protected by write-once ledger.'
  },
  {
    id: 'ALT-002',
    type: 'Unauthorized Access Attempt',
    severity: 'High',
    title: 'Unusual bulk download from a restricted case',
    description: 'User account USR-009 attempted 14 consecutive full-resolution document export requests within 90 seconds from an unrecognized subnet.',
    timestamp: '2026-09-02 03:45:18',
    relatedResource: 'Case JV-2026-002 (Cyber Fraud Investigation)',
    relatedCaseId: 'CASE-002',
    status: 'New',
    recommendedAction: 'Temporarily throttle session export bandwidth, prompt for step-up biometric MFA, and notify Directorate of Information Security.',
    assignedInvestigator: 'Dr. Sarah Jenkins'
  },
  {
    id: 'ALT-003',
    type: 'Pending Approval Deadline',
    severity: 'Medium',
    title: 'Approval deadline approaching',
    description: 'Mandatory prosecution review for SCADA reverse-engineering evidence (DOC-005) expires in under 72 hours before the judicial hearing.',
    timestamp: '2026-09-02 08:00:00',
    relatedResource: 'Malware_Reverse_Engineering_Report_LockBitX.pdf',
    relatedCaseId: 'CASE-002',
    status: 'New',
    recommendedAction: 'Send automated priority notification to Adv. Vikramaditya Sen and designate backup signing officer.'
  }
];

export const INITIAL_SETTINGS: SystemSettings = {
  organizationName: 'JusticeVault National Legal & Forensic Network',
  agencyCode: 'JV-GOV-CENTRAL',
  jurisdiction: 'National Judicial & Law Enforcement Directorate',
  mfaEnforcement: 'Mandatory for All',
  sessionTimeoutMinutes: 30,
  passwordMinLength: 12,
  passwordExpiryDays: 90,
  maxFailedLoginAttempts: 3,
  defaultRetentionYears: 10,
  allowedFileExtensions: ['PDF', 'DOCX', 'XLSX', 'JPG', 'PNG', 'MP4', 'WAV', 'TXT'],
  maxUploadSizeBytes: 104857600, // 100 MB
  blockchainNetworkName: 'JusticeLedger-Permissioned-Quorum-Simulated',
  blockchainBlockTimeSeconds: 3,
  consensusAlgorithm: 'Istanbul BFT (Simulated Byzantine Fault Tolerant Proof-of-Authority)',
  backupSchedule: 'Hourly',
  lastBackupTime: '2026-09-02 09:00:00 UTC',
  backupStatus: 'Healthy',
  prototypeMode: true
};

export const INITIAL_BORDER_INTERCEPTS: BorderInterceptRecord[] = [
  {
    id: 'BRD-001',
    checkpointId: 'CP-SEC7-01',
    checkpointName: 'Sector 7 High-Altitude Pass',
    sector: 'Northern Frontier Command',
    timestamp: '2026-09-02 02:44:19 UTC',
    interceptType: 'UAV Drone Sighting',
    threatSeverity: 'Critical',
    suspectEntityOrVehicle: 'Low-RCS Quadcopter UAV (Payload Equipped)',
    coordinates: '34.2198° N, 74.5210° E',
    evidenceHash: '7c89def0123456789abcdef0123456789abcdef0123456789abcdef012345678',
    blockchainBlock: 489319,
    status: 'Intercepted',
    details: 'Low-radar cross-section surveillance drone forced down using directional RF tactical jammer. Recovered payload contained encrypted satellite transceivers and high-gain antenna.',
    assignedUnit: '7th Border Surveillance Battalion'
  },
  {
    id: 'BRD-002',
    checkpointId: 'CP-HBR-04',
    checkpointName: 'Harbor Logistics Marine Gate 4',
    sector: 'Western Naval Coast Command',
    timestamp: '2026-09-02 06:15:30 UTC',
    interceptType: 'Maritime Cargo Discrepancy',
    threatSeverity: 'High',
    suspectEntityOrVehicle: 'Container MSC-88190 (Declared: Agri-Pumps)',
    coordinates: '18.9432° N, 72.8421° E',
    evidenceHash: '8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c',
    blockchainBlock: 489312,
    status: 'Quarantined',
    details: 'Dual-use electronic radar scramblers concealed inside false casing of industrial agricultural pumps. Bill of lading cryptographic hash failed customs registry check.',
    assignedUnit: 'Coast Guard Port Interdiction Wing'
  },
  {
    id: 'BRD-003',
    checkpointId: 'CP-ALP-02',
    checkpointName: 'Northern Alpine Checkpoint Bravo',
    sector: 'Northern Frontier Command',
    timestamp: '2026-09-01 19:30:12 UTC',
    interceptType: 'Biometric Mismatch',
    threatSeverity: 'Critical',
    suspectEntityOrVehicle: 'Traveler Credential ID #P-902188',
    biometricMatchConfidence: 28.4,
    coordinates: '32.7266° N, 74.8570° E',
    evidenceHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    blockchainBlock: 489304,
    status: 'Escalated to Military Intel',
    details: 'Live 3D infrared facial mesh flagged 71.6% variance against biometric passport chip signature. Digital signature revoked; suspect transferred for identity verification.',
    assignedUnit: 'Immigration Security & Counter-Terror Task Force'
  },
  {
    id: 'BRD-004',
    checkpointId: 'CP-HWY-03',
    checkpointName: 'National Highway Intercept Post Delta-3',
    sector: 'Capital Defense Belt',
    timestamp: '2026-09-01 14:10:00 UTC',
    interceptType: 'Vehicle Anomaly',
    threatSeverity: 'High',
    suspectEntityOrVehicle: 'Reinforced Freight Van (Plate: DL-01-X-4912)',
    anprLicensePlate: 'DL-01-X-4912',
    coordinates: '28.6139° N, 77.2090° E',
    evidenceHash: '5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
    blockchainBlock: 489291,
    status: 'Intercepted',
    details: 'Automated Number Plate Recognition (ANPR) optical system alerted on duplicated registration tags matching blacklisted cross-border weapons transit dossier.',
    assignedUnit: 'Highway Patrol Special Operations'
  }
];

export const INITIAL_SIGINT_RECORDS: SigintRecord[] = [
  {
    id: 'SIG-001',
    interceptFrequency: '8.412 GHz (Mil X-Band)',
    protocol: 'Satellite Mil-Band',
    capturedTimestamp: '2026-09-02 02:35:12 UTC',
    originGeoEstimate: 'Border Mountain Ridge Quadrant 4B (Sector 7)',
    encryptionCipher: 'Modified Serpent-256 + Linear Feedback Shift',
    decryptionStatus: 'Cracked (AI Lattice Engine)',
    classification: 'TOP SECRET // SAP',
    extractedKeywords: ['Logistics Drop', 'Rendezvous Point Alpha', 'Cipher Re-seed', 'Safehouse 9'],
    rawTranscriptSnippet: '"...Confirming drone drop at Sector 7 ridge. Ground team deployed with tactical transceivers. Standby for acoustic diversion at 02:40 UTC..."',
    judicialWarrantNumber: 'FISA-WAR-2026-0988 (Section 65B Certified)',
    sha256Hash: '3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b',
    blockchainTx: '0xDEF2026SIG9911AA'
  },
  {
    id: 'SIG-002',
    interceptFrequency: '433.920 MHz (UHF FHSS)',
    protocol: 'Burst Transceiver',
    capturedTimestamp: '2026-09-02 05:18:40 UTC',
    originGeoEstimate: 'Coastal Estuary Grid 11 (Naval Sector)',
    encryptionCipher: 'ChaCha20-Poly1305 with Pre-Shared Ephemeral Keys',
    decryptionStatus: 'Partial Decryption',
    classification: 'TOP SECRET',
    extractedKeywords: ['Frequency Offset', 'Signal Beacon', 'Encrypted Payload', 'Drone Return'],
    rawTranscriptSnippet: '"...Beacon frequency offset 12 kHz. Handshake packet acknowledged. Maritime storage node offline until relay confirms hash match..."',
    judicialWarrantNumber: 'MIL-INT-ORD-4412 (National Security Council)',
    sha256Hash: '4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c',
    blockchainTx: '0xDEF2026SIG8844BB'
  },
  {
    id: 'SIG-003',
    interceptFrequency: 'Multi-Hop Onion Relay (Port 9050)',
    protocol: 'Darknet Mesh Packet',
    capturedTimestamp: '2026-09-01 21:10:00 UTC',
    originGeoEstimate: 'Egress Point: Zurich Gateway Node 04',
    encryptionCipher: 'RSA-4096 + AES-256 GCM Hybrid Envelope',
    decryptionStatus: 'Cracked (AI Lattice Engine)',
    classification: 'SECRET',
    extractedKeywords: ['Exfiltration Buffer', 'SCADA Target', 'Memory Extraction', 'Mirror Vault'],
    rawTranscriptSnippet: '"...Municipal utility controller memory image exfiltrated successfully. Private key split across 3 cold offline ledgers. Ransom countdown active..."',
    judicialWarrantNumber: 'CYB-TRIB-2026-1102 (Tribunal Authorization)',
    sha256Hash: '5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
    blockchainTx: '0xDEF2026SIG7722CC'
  }
];

export const INITIAL_DEFENCE_DOSSIERS: DefenceIntelDossier[] = [
  {
    id: 'DOS-001',
    operationCodename: 'OPERATION BORDER SENTINEL',
    theatre: 'Northern Frontier Sector & High Altitude Passes',
    classification: 'TOP SECRET // SAP',
    threatLevel: 'Critical',
    leadAgency: 'Joint Defence Intelligence & Border Command',
    participatingAgencies: ['Border Security Command', 'Military Intelligence', 'Metropolitan Police Cyber Cell', 'Directorate of Information Security'],
    status: 'Active Engagement',
    lastSatelliteSync: '2026-09-02 11:45:00 UTC',
    airGappedVaultStatus: 'Synchronized & Sealed',
    summary: 'Joint defense counter-infiltration operation countering coordinated high-altitude drone incursions, unauthorized satellite communications, and clandestine supply drops across Sector 7.',
    aiThreatScore: 94,
    keyIntelligenceFindings: [
      'Hostile quadcopter UAV telemetry confirmed recurring high-altitude reconnaissance flights over restricted ammunition depot.',
      'Biometric 3D facial scan mismatch at Checkpoint Bravo correlated with intercepted satellite burst communications.',
      'Air-gapped HSM sovereign vault successfully synchronized with zero leakage.'
    ],
    associatedDocumentIds: ['DOC-009', 'DOC-010', 'DOC-012'],
    tacticalDirectives: [
      'Deploy RF anti-drone directional jammers across Sector 7 perimeter.',
      'Enforce mandatory biometric 10-print checks on all freight vehicles.',
      'Transmit evidentiary package to Military Tribunal under Section 65B certification.'
    ]
  },
  {
    id: 'DOS-002',
    operationCodename: 'OPERATION IRON SHIELD',
    theatre: 'Maritime Logistics & Coastal Critical Infrastructure',
    classification: 'TOP SECRET',
    threatLevel: 'High',
    leadAgency: 'Coast Guard & Naval Intelligence Wing',
    participatingAgencies: ['Coast Guard', 'Customs Forensic Directorate', 'Central Law Enforcement Agency'],
    status: 'Under Surveillance',
    lastSatelliteSync: '2026-09-02 09:20:00 UTC',
    airGappedVaultStatus: 'Synchronized & Sealed',
    summary: 'Maritime border security initiative defending critical port supply chains and container shipping lanes from contraband exfiltration and dual-use cyber sabotage hardware.',
    aiThreatScore: 78,
    keyIntelligenceFindings: [
      'Clandestine radio transmitter identified inside false-bottom container MSC-88190.',
      'Cryptographic shipping seals showed micro-tampering detected by forensic laser spectroscopy.'
    ],
    associatedDocumentIds: ['DOC-004', 'DOC-011'],
    tacticalDirectives: [
      'Quarantine Container Terminal 4 berths.',
      'Execute bit-stream forensic acquisition of ship navigational black-box logs.'
    ]
  },
  {
    id: 'DOS-003',
    operationCodename: 'OPERATION DEEP CIPHER',
    theatre: 'National Cyber Defense & Critical SCADA Systems',
    classification: 'TOP SECRET // SAP',
    threatLevel: 'Critical',
    leadAgency: 'Defence Cyber Agency (DCA)',
    participatingAgencies: ['DCA', 'Central Forensic Science Laboratory', 'National Cyber Security Tribunal'],
    status: 'Active Engagement',
    lastSatelliteSync: '2026-09-02 12:10:00 UTC',
    airGappedVaultStatus: 'Synchronized & Sealed',
    summary: 'Strategic cyber defense operation safeguarding municipal electrical grids, water treatment telemetry, and military communications from ransomware extortion syndicates.',
    aiThreatScore: 91,
    keyIntelligenceFindings: [
      'Zero-day industrial controller ransomware payload weaponized against regional electrical grid transformers.',
      'Malware command-and-control communications routed through darknet mesh nodes.'
    ],
    associatedDocumentIds: ['DOC-005', 'DOC-006', 'DOC-010'],
    tacticalDirectives: [
      'Isolate electrical substation SCADA control loops to physical air-gap.',
      'Submit memory dump forensic reports to National Security Council.'
    ]
  }
];
